version: "2"
services:
  knowledge:
    container_name: knowledge
    # image: koda/docker-knowledge
    build: .
    volumes:
      - ./logs:/usr/local/tomcat/logs
      - ./volumes/knowledge:/root/.knowledge
    environment:
      KNOWLEDGE_HOME: /home/knowledge
    ports:
      - "8082:8080"
    restart: always
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "3"
  db:
    container_name: knowledge-db
    image: postgres:12.13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=knowledge_production
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "3"
